### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by wogsland**
I really like this tool so I want to make it better. Basically I made the database setup into a script that would allow the user to easily add these tables to an existing database, cleaned up some code duplication, changed references to ruddfawcett's repo to the HabitRPG repo (Rudd has emptied his repo of code), and rewrote the README to reflect the changes in setup.

### CODE REVIEW

**Comment by lefnire** [comment]
@wogsland ours is actually a stale fork of @ruddfawcett's project. His is likely to be more up-to-date than ours. Rudd, you still maintaining? If so, do we wanna take this PR to your repo, or should I rebase your latest changes then merge this here?

**Comment by wogsland** [comment]
@lefnire If you look at @ruddfawcett's project, he deleted all the files in February except the README.md, which is why I submitted the pull request to this repo rather than his.

**Comment by lefnire** [comment]
Fair 'nuff! I'll merge this and wait to hear back from @ruddfawcett in case there's any other input. In the mean time, I'll make @wogsland the repo admin on this (if you're willing)

**Comment by wogsland** [comment]
Sure thing. Thanks!

**Comment by ruddfawcett** [comment]
@wogsland @lefnire Ha, made this a few years ago (2 I think?).  Didn't have time to really hammer bugs - and if I remember correctly, I couldn't get it to work 90% of the time?  

That's awesome if you cleaned it up - I'd still be happy to host it.

**Comment by wogsland** [comment]
@ruddfawcett Yeah, it is pretty buggy but I like the idea so I'm going to go through it pretty methodically and hammer them out. Don't have huge amounts of spare time to devote to it so we'll see how it goes. I've actually got the whole family playing HabitRPG. Great way to assign the kids chores. After I get the GitHub interaction solid I'm planning to build in interaction with Stash and Beanstalk as well. Love to work on it with you if you're interested.

**Pull request merged**
